# model_checkpoint:
#   _target_: lightning.pytorch.callbacks.ModelCheckpoint
#   monitor: "val/acc" # name of the logged metric which determines when model is improving
#   mode: "max" # can be "max" or "min"
#   save_top_k: 1 # save k best models (determined by above metric)
#   save_last: True # additionaly always save model from last epoch
#   verbose: False
#   dirpath: "checkpoints/"
#   filename: "epoch_{epoch:03d}"
#   auto_insert_metric_name: False

model_checkpoint_on_step:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: null # name of the logged metric which determines when model is improving
  mode: "max" # can be "max" or "min"
  every_n_epochs: 1 # truncated length of MNLI train / 16
  verbose: true
  save_top_k: -1 # -1 -> all models are saved
  save_last: true # additionaly always save model from last epoch
  dirpath: "checkpoints/"
  auto_insert_metric_name: false

# early_stopping:
#   _target_: lightning.pytorch.callbacks.EarlyStopping
#   monitor: "val/acc" # name of the logged metric which determines when model is improving
#   mode: "max" # can be "max" or "min"
#   patience: 100 # how many epochs of not improving until training stops
#   min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

learning_rate:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "step"
